### RUN ON: 
# Push to main branch (after PR merge).

### JOBS:
# Generate and upload build files.
# Push build files to S3.

name: 'Deploy Application'
on:
  push:
    branches:
      - main

  workflow_dispatch: 

jobs:
  create_dist:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Get code
        uses: actions/checkout@v6

      - name: Cache deps
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: deps-node-module-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install deps
        run: npm ci

      - name: Create dist
        run: npm run build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist-files
          path: dist
          if-no-files-found: error